site_name: netschoolapi
site_description: 'Документация библиотеки netschoolapi: методы, классы и их поля'
site_author: Иван Горланов
copyright: Даниил Николаев, Иван Горланов, Елисей Власенко

repo_url: https://github.com/nm17/netschoolapi

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - toc:
      permalink: True
  - smarty:
      smart_angled_quotes: True

nav:
  - index.md
  - guide.md
  - reference.md

theme: readthedocs

extra:
  version: 5.0.2
